services:
  postgres:
    image: postgres:14
    container_name: casino-mis-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5452:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"

  casino-mis-application:
    build:
      context: .
      dockerfile: casino-mis-application/Dockerfile
    container_name: casino-mis-application
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: jdbc:postgresql://casino-mis-postgres:5432/casino_mis
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
