global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'casino-mis-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['casino-mis-application:8080']
        labels:
          application: 'casino-mis'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']